#%RAML 1.0 DataType
properties: 
  name:
    type: string
    example: "Something"
  email:
    type: string
    example: "something@nothing.com"
  phone?:
    type: number
    example: 9807654321
  revenue?:
    type: number
    example: 99998
  street?:
    type: string
    example: "345 Nowhere St"
  city?:
    type: string
    example: "everywhere"
  zipcode?:
    type: number
    example: 87654
  country?:
    type: string
    example: "I DON'T KNOW"