#RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          {
            "error" : "Bad Request"
          }
  404:
    body:
      application/json:
        example:
          {
            "error" : "Not Found"
          }
  500:
    body:
      application/json:
        example:
          {
            "error" : "Internal Server Error"
          }
  503:
    body:
      application/json:
        example:
          {
            "error" : "Service Unavailable"
          }